In [148]:
import yfinance as yf
import pandas as pd
import numpy as np

In [166]:

ticker = 'MSFT'
df = yf.download(ticker)
df.index = pd.to_datetime(df.index)
# df.drop(columns="Adj Close", inplace=True)
df

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,
1986-03-13 00:00:00+00:00,0.059946,0.097222,0.101563,0.088542,0.088542,1031788800
1986-03-14 00:00:00+00:00,0.062087,0.100694,0.102431,0.097222,0.097222,308160000
1986-03-17 00:00:00+00:00,0.063158,0.102431,0.103299,0.100694,0.100694,133171200
1986-03-18 00:00:00+00:00,0.061552,0.099826,0.103299,0.098958,0.102431,67766400
1986-03-19 00:00:00+00:00,0.060482,0.098090,0.100694,0.097222,0.099826,47894400
...,...,...,...,...,...,...
2024-11-07 00:00:00+00:00,425.429993,425.429993,426.850006,419.880005,421.279999,19901800
2024-11-08 00:00:00+00:00,422.540009,422.540009,426.500000,421.779999,425.320007,16891400
2024-11-11 00:00:00+00:00,418.010010,418.010010,424.809998,416.000000,422.519989,24503300
2024-11-12 00:00:00+00:00,423.029999,423.029999,424.440002,417.200012,418.250000,19401200
2024-11-13 00:00:00+00:00,425.200012,425.200012,429.329987,418.209991,421.640015,21477900

In [167]:
df["change_tomorrow"] = df["Close"].pct_change(-1)*100
df = df.dropna().copy()
df

Price,Adj Close,Close,High,Low,Open,Volume,change_tomorrow
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,
Date,,,,,,,
1986-03-13 00:00:00+00:00,0.059946,0.097222,0.101563,0.088542,0.088542,1031788800,-3.448071
1986-03-14 00:00:00+00:00,0.062087,0.100694,0.102431,0.097222,0.097222,308160000,-1.695774
1986-03-17 00:00:00+00:00,0.063158,0.102431,0.103299,0.100694,0.100694,133171200,2.609539
1986-03-18 00:00:00+00:00,0.061552,0.099826,0.103299,0.098958,0.102431,67766400,1.769803
1986-03-19 00:00:00+00:00,0.060482,0.098090,0.100694,0.097222,0.099826,47894400,2.727102
...,...,...,...,...,...,...,...
2024-11-06 00:00:00+00:00,420.179993,420.179993,420.450012,410.519989,412.420013,26681800,-1.234046
2024-11-07 00:00:00+00:00,425.429993,425.429993,426.850006,419.880005,421.279999,19901800,0.683955
2024-11-08 00:00:00+00:00,422.540009,422.540009,426.500000,421.779999,425.320007,16891400,1.083706
2024-11-11 00:00:00+00:00,418.010010,418.010010,424.809998,416.000000,422.519989,24503300,-1.186674
2024-11-12 00:00:00+00:00,423.029999,423.029999,424.440002,417.200012,418.250000,19401200,-0.510351

In [168]:
df["change_tomorrow_direction"] = df.change_tomorrow.apply(lambda v: "UP" if v>0 else "DOWN")
df

Price,Adj Close,Close,High,Low,Open,Volume,change_tomorrow,change_tomorrow_direction
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT,,
Date,,,,,,,,
1986-03-13 00:00:00+00:00,0.059946,0.097222,0.101563,0.088542,0.088542,1031788800,-3.448071,DOWN
1986-03-14 00:00:00+00:00,0.062087,0.100694,0.102431,0.097222,0.097222,308160000,-1.695774,DOWN
1986-03-17 00:00:00+00:00,0.063158,0.102431,0.103299,0.100694,0.100694,133171200,2.609539,UP
1986-03-18 00:00:00+00:00,0.061552,0.099826,0.103299,0.098958,0.102431,67766400,1.769803,UP
1986-03-19 00:00:00+00:00,0.060482,0.098090,0.100694,0.097222,0.099826,47894400,2.727102,UP
...,...,...,...,...,...,...,...,...
2024-11-06 00:00:00+00:00,420.179993,420.179993,420.450012,410.519989,412.420013,26681800,-1.234046,DOWN
2024-11-07 00:00:00+00:00,425.429993,425.429993,426.850006,419.880005,421.279999,19901800,0.683955,UP
2024-11-08 00:00:00+00:00,422.540009,422.540009,426.500000,421.779999,425.320007,16891400,1.083706,UP
2024-11-11 00:00:00+00:00,418.010010,418.010010,424.809998,416.000000,422.519989,24503300,-1.186674,DOWN
2024-11-12 00:00:00+00:00,423.029999,423.029999,424.440002,417.200012,418.250000,19401200,-0.510351,DOWN

In [169]:
dftrain = df.loc["2010-01-01":"2022-12-13",:].copy().drop(columns=["change_tomorrow","change_tomorrow_direction"])
dftest =  df.loc["2023-01-01":,:].copy().drop(columns=["change_tomorrow","change_tomorrow_direction"])

In [170]:
ttrain = df.loc["2010-01-01":"2022-12-13","change_tomorrow_direction"].copy()
ttest  = df.loc["2023-01-01":,"change_tomorrow_direction"].copy()

In [171]:
from sklearn.tree import DecisionTreeClassifier

In [172]:
model_dt = DecisionTreeClassifier(max_depth=6)
model_dt.fit(X=dftrain, y=ttrain)

DecisionTreeClassifier(max_depth=6)

In [173]:
from sklearn.tree import plot_tree
#plot_tree(decision_tree=model_dt);

In [174]:
ptrain = model_dt.predict(X=dftrain)
ptest = model_dt.predict(X=dftest)

In [175]:
Vtrain = (ptrain == ttrain).sum()/len(ptrain)
Vtest = (ptest == ttest).sum()/len(ptest)

In [176]:
print(f"Success rate train = {Vtrain}\nSuccess rate test  = {Vtest}")

Success rate train = 0.5687116564417178
Success rate test  = 0.4989339019189765

In [177]:
from backtesting import Backtest, Strategy

In [178]:
already_bought = False
list_buy_sell = []
for d in ttrain:
    if d=='UP' and already_bought == False:
        list_buy_sell.append(1)
        already_bought = True
    elif d=='DOWN' and already_bought == True:
        list_buy_sell.append(-1)
        already_bought = False
    else:
        list_buy_sell.append(0)

In [179]:
track = pd.DataFrame({"direction":ttrain, "buy_sell":list_buy_sell})
track

                          direction  buy_sell
Date
2010-01-04 00:00:00+00:00      DOWN         0
2010-01-05 00:00:00+00:00        UP         1
2010-01-06 00:00:00+00:00        UP         0
2010-01-07 00:00:00+00:00      DOWN        -1
2010-01-08 00:00:00+00:00        UP         1
...                             ...       ...
2022-12-07 00:00:00+00:00      DOWN        -1
2022-12-08 00:00:00+00:00        UP         1
2022-12-09 00:00:00+00:00      DOWN        -1
2022-12-12 00:00:00+00:00      DOWN         0
2022-12-13 00:00:00+00:00      DOWN         0

[3260 rows x 2 columns]

In [180]:
class ClassificationUP(Strategy):
    def init(self):
        self.model = model_dt
        self.already_bought = False

    def next(self):
        explanatory_today = self.data.df.iloc[[-1],:]
        forecast_tomorrow = self.model.predict(explanatory_today)[0]

        if forecast_tomorrow == 'UP' and self.already_bought == False:
            self.buy()
            self.already_bought = True
        elif forecast_tomorrow == 'DOWN' and self.already_bought == True:
            self.sell()
            self.already_bought = False
        else:
            pass

In [181]:
bt = Backtest(data=dftrain, strategy=ClassificationUP, cash=10000, commission=.002, exclusive_orders=True)

TypeError: other must be a MultiIndex or a list of tuples

In [165]:
dftrain.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,MSFT,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,
2010-01-04 00:00:00+00:00,23.347322,30.950001,31.100000,30.590000,30.620001,38409100
2010-01-05 00:00:00+00:00,23.354856,30.959999,31.100000,30.639999,30.850000,49749600
2010-01-06 00:00:00+00:00,23.211535,30.770000,31.080000,30.520000,30.879999,58182400
2010-01-07 00:00:00+00:00,22.970146,30.450001,30.700001,30.190001,30.629999,50559700
2010-01-08 00:00:00+00:00,23.128555,30.660000,30.879999,30.240000,30.280001,51197400